const advanced = {
  id: "advanced",
  name: "Advanced",
  shortName: "ADV",
  totalWeeks: 8,
  tagline: "ADVANCED · BJJ",
  description: "Advanced · BJJ Functional Strength · F22 + Bowflex 1090",
  days: [
    {
      id: "A", label: "Pull + Biceps", emoji: "💪",
      color: "#2563EB", colorDim: "#1D3B8A22",
      warmup: "Band pull-aparts 3×15, dead hang 3×20s, cat-cow 10 reps",
      exercises: [
        { name: "Weighted Pull-Ups", sets: 4, reps: "5", note: "F22 pull-up bar. Add weight via dumbbell between feet. Full ROM.", spine: false },
        { name: "Cable Face Pulls", sets: 3, reps: "15", note: "F22 high cable. Thumbs to ears, externally rotate.", spine: false },
        { name: "Single-Arm DB Row", sets: 4, reps: "10 ea.", note: "Brace on bench, neutral spine. Heavy. Drive elbow to hip.", spine: false },
        { name: "Cable Low Row", sets: 3, reps: "12", note: "F22 low cable, seated. Retract scapula, pause at chest.", spine: false },
        { name: "Towel / Gi Grip Dead Hang", sets: 3, reps: "30s", note: "Hang a towel over pull-up bar, grip both ends. Accumulate hang time.", spine: false },
        { name: "Hammer Curl", sets: 4, reps: "10 ea.", note: "Neutral grip (thumbs up). Alternate or simultaneous. Control the eccentric.", spine: false },
        { name: "Incline Dumbbell Curl", sets: 3, reps: "12", note: "Bench at 45°. Full stretch at bottom, supinate at top. Slow.", spine: false },
        { name: "Dead Bug", sets: 3, reps: "8 ea.", note: "Press lower back INTO floor throughout. No lumbar arch.", spine: true },
        { name: "Pallof Press", sets: 3, reps: "12 ea.", note: "F22 mid-cable, perpendicular stance. Resist rotation, don't twist.", spine: true },
      ],
    },
    {
      id: "B", label: "Lower + Hinge", emoji: "🦵",
      color: "#16A34A", colorDim: "#14532D22",
      warmup: "Hip circles 2×10, glute bridges 2×15, banded clams 2×15",
      exercises: [
        { name: "Bulgarian Split Squat", sets: 4, reps: "8 ea.", note: "Rear foot elevated. Hold dumbbells. Keep torso upright.", spine: true },
        { name: "DB Romanian Deadlift", sets: 4, reps: "10", note: "Hinge at hips, soft knee, neutral spine. Feel hamstring stretch at bottom.", spine: true },
        { name: "Cable Pull-Through", sets: 3, reps: "15", note: "F22 low cable between legs. Hip hinge, squeeze glutes at top.", spine: true },
        { name: "Goblet Squat", sets: 3, reps: "12", note: "Hold one dumbbell at chest. Upright torso, push knees out.", spine: false },
        { name: "Single-Leg RDL", sets: 3, reps: "8 ea.", note: "Balance on one leg, hinge to parallel. Hold dumbbell opposite hand.", spine: true },
        { name: "McGill Side Plank", sets: 3, reps: "30s ea.", note: "Elbow under shoulder, body straight. One of the McGill Big 3.", spine: true },
        { name: "Bird Dog", sets: 3, reps: "8 ea.", note: "Extend opposite arm/leg. Hold 2s at top. No hip rotation.", spine: true },
      ],
    },
    {
      id: "C", label: "Press + Triceps", emoji: "🏋️",
      color: "#7C3AED", colorDim: "#4C1D9522",
      warmup: "Thoracic rotations 2×10, shoulder circles, wrist prep",
      exercises: [
        { name: "DB Floor Press", sets: 4, reps: "8", note: "Lie on floor, elbows at 45°. Limits shoulder over-extension.", spine: false },
        { name: "Seated DB Overhead Press", sets: 4, reps: "8", note: "Back supported. Don't flare elbows. Control the descent.", spine: false },
        { name: "Landmine Press", sets: 3, reps: "10 ea.", note: "Wedge barbell in F22 corner. Single arm, press at angle.", spine: false },
        { name: "Cable Woodchop (High→Low)", sets: 3, reps: "12 ea.", note: "F22 high cable. Rotate from hip — not just arms. Athletic stance.", spine: true },
        { name: "Cable Woodchop (Low→High)", sets: 3, reps: "12 ea.", note: "F22 low cable. Mirror of above. Drive from hips and core.", spine: true },
        { name: "Lateral Raise", sets: 3, reps: "15", note: "Controlled tempo, slight forward tilt. Keep traps out of it.", spine: false },
        { name: "Skull Crushers (DB)", sets: 3, reps: "12", note: "Lower to temples, elbows at ceiling. Full stretch at bottom.", spine: false },
        { name: "Tricep Pushdown (Cable)", sets: 3, reps: "15", note: "F22 high cable, rope. Elbows pinned, spread rope at bottom.", spine: false },
        { name: "Overhead Tricep Extension", sets: 3, reps: "12", note: "F22 high cable, rope, face away. Elbows close to head.", spine: false },
        { name: "McGill Curl-Up", sets: 3, reps: "8", note: "Hands under lumbar. Lift only head & shoulders. Spine neutral.", spine: true },
      ],
    },
    {
      id: "D", label: "Accessory", emoji: "🔄",
      color: "#EA580C", colorDim: "#7C2D1222",
      optional: true,
      warmup: "Light movement, foam roll hips and thoracic spine",
      exercises: [
        { name: "Neck Work (Manual / Harness)", sets: 3, reps: "15 ea.", note: "All 4 directions. Light resistance. Critical for BJJ, often neglected.", spine: false },
        { name: "Farmer's Carry", sets: 4, reps: "40 yd", note: "Heavy dumbbells, tall posture. Try single-arm for anti-lateral core.", spine: true },
        { name: "Zottman Curl", sets: 3, reps: "10", note: "Curl up supinated, rotate to pronated at top, lower slow.", spine: false },
        { name: "Cable Pull-Apart", sets: 3, reps: "20", note: "Shoulder height. Light weight, high reps.", spine: false },
        { name: "Hip Flexor Stretch + 90/90", sets: 2, reps: "60s ea.", note: "Tight hip flexors increase L4/L5 stress — essential for BJJ athletes.", spine: true },
        { name: "Hollow Body Hold", sets: 3, reps: "25s", note: "Compress lower back into floor the whole time. Scale by bending knees.", spine: true },
        { name: "Thoracic Foam Roll", sets: 1, reps: "2–3 min", note: "Upper and mid back only. Avoid rolling the lumbar region.", spine: true },
      ],
    },
  ],
  rules: [
    ["Rest between sets", "90–120s compound lifts · 60s accessories"],
    ["Deload every 4–6 wks", "Cut volume 40% — you're also doing BJJ 3–4×"],
    ["Progress weekly", "Add weight or reps each session. Log everything."],
    ["Neutral spine first", "Reduce weight before compromising form on any 🦴 exercise"],
    ["Stop if leg tingles", "Radiating pain or numbness = nerve signal. Rest and reassess."],
  ],
};

export default advanced;
